name: Publish To GPR
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  publish-to-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # For Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js And Setup .npmrc
        uses: actions/setup-node@v6
        with:
          node-version: latest
          registry-url: 'https://npm.pkg.github.com'
          scope: '@neos21'
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run : npm install
      - name: Build
        run : npm run build
      - name: Publish
        run : npm publish
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
